force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/Current_Traffic__c.field-meta.xml
<CustomField>
    <fullName>Current_Traffic__c</fullName>
    <label>Current Traffic</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/Entrances__c.field-meta.xml
<CustomField>
    <fullName>Entrances__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Monitored Store Entrances</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/Maximum_Traffic__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Traffic__c</fullName>
    <label>Maximum Traffic</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/Store_Account__c.field-meta.xml
<CustomField>
    <fullName>Store_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Stores</relationshipLabel>
    <relationshipName>Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/Store_Number__c.field-meta.xml
<CustomField>
    <fullName>Store_Number__c</fullName>
    <label>Store Number</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/Total_Traffic__c.field-meta.xml
<CustomField>
    <fullName>Total_Traffic__c</fullName>
    <label>Total Traffic</label>
    <summarizedField>Store_Date__c.Total_Traffic__c</summarizedField>
    <summaryForeignKey>Store_Date__c.Store__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Store_Date__c/Store_Date__c.object-meta.xml
<CustomObject>
    <label>Store Date</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}-{0000}</displayFormat>
        <label>Store Date</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Date__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Store Dates</relationshipLabel>
    <relationshipName>Store_Dates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Store_Date__c/fields/Total_Traffic__c.field-meta.xml
<CustomField>
    <fullName>Total_Traffic__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Traffic</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Traffic_Change_Event__e/Traffic_Change_Event__e.object-meta.xml
<CustomObject>
    <label>Traffic Change Event</label>
    <pluralLabel>Traffic Change Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Traffic_Change_Event__e/fields/Change_Value__c.field-meta.xml
<CustomField>
    <fullName>Change_Value__c</fullName>
    <label>Change Value</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Traffic_Change_Event__e/fields/Store_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Store_Record_Id__c</fullName>
    <label>Store Record Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StoreTrafficController.cls
public with sharing class StoreTrafficController {
    
    private final static Integer MAX_RESULTS = 5;

    @AuraEnabled(cacheable=true)
    public static List<LookupSearchResult> search(String searchTerm, List<String> selectedIds, String anOptionalParam) {
        // Prepare query paramters
        searchTerm += '*';

        // Execute search query
        List<List<SObject>> searchResults = [FIND :searchTerm IN ALL FIELDS RETURNING
            Store__c (Id, Name, Maximum_Traffic__c, Store_Number__c WHERE id NOT IN :selectedIds)
            LIMIT :MAX_RESULTS];

        // Prepare results
        List<LookupSearchResult> results = new List<LookupSearchResult>();

        // Extract Accounts & convert them into LookupSearchResult
        String storeIcon = 'custom:custom50';
        Store__c [] stores = ((List<Store__c>) searchResults[0]);
        for (Store__c store : stores) {
            results.add(new LookupSearchResult(store.Id, 'Store', storeIcon, store.Name, 'Store • '+ store.Store_Number__c));
        }
        return results;
    }

    @AuraEnabled
    public static LookupSearchResult initSelection(String UserId){

        String storeIcon = 'custom:custom50';
        
        if (UserId == '') {
                throw new AuraHandledException('No User Provided');
        }
        
        Id accId = [SELECT contactId, contact.AccountId FROM User WHERE Id = :UserId].contact.AccountId;
        Store__c store = [SELECT Id, Name, Maximum_Traffic__c, Store_Number__c FROM Store__c WHERE Store_Account__c = :accId];

        LookupSearchResult result = new LookupSearchResult(store.Id, 'Store', storeIcon, store.Name, 'Store • '+ store.Store_Number__c);

        return result;
    }

    @AuraEnabled
    public static Store__c storeDetail(String storeId) {
        
        Store__c thisStore = [SELECT Id, Entrances__c, Current_Traffic__c, Maximum_Traffic__c FROM Store__c WHERE Id = :storeId];
        System.debug(thisStore);
        return thisStore;
    }

    @AuraEnabled
    public static Store__c changeTraffic(String storeId, String changeDir) {
        System.debug(storeId);

        Store__c thisStore = [SELECT Id, Entrances__c, Current_Traffic__c, Maximum_Traffic__c FROM Store__c WHERE Id = :storeId];
        System.debug(thisStore);

        Store_Date__c storeDateToday = null;
        System.debug(storeDateToday);
        Date today = date.today();

        try{
            storeDateToday = [SELECT Id, Total_Traffic__c, Store__c, Date__c FROM Store_Date__c WHERE Store__c = :thisStore.Id AND Date__c = :today];
        } catch(Exception ex){
            storeDateToday = new Store_Date__c(Store__c=thisStore.Id,Date__c=today,Total_Traffic__c=0);
            insert storeDateToday;
        }

        
        System.debug(storeDateToday);

        Integer changeVal = 0;
        
        if (changeDir == 'Increment') {
            if (thisStore.Current_Traffic__c >= thisStore.Maximum_Traffic__c) {
                throw new AuraHandledException('Cannot increase traffic');
            }
            thisStore.Current_Traffic__c++;
            changeVal = 1;
            storeDateToday.Total_Traffic__c++;
        }

        if (changeDir == 'Decrement') {
            thisStore.Current_Traffic__c--;
            changeVal = -1;
        }
    
        System.debug(thisStore);
        System.debug(storeDateToday);
        update thisStore;
        update storeDateToday;

        //Traffic_Change_Event__e trafEvent = new Traffic_Change_Event__e(Store_Record_Id__c=storeId,Change_Value__c=changeVal);
        //Database.SaveResult result = EventBus.publish(trafEvent);
        //System.debug(trafEvent);

        //if (result.isSuccess()) {
        //    System.debug('Successfully published event.');
        //} else {
        //    for(Database.Error err : result.getErrors()) {
        //        System.debug('Error returned: ' +
        //                    err.getStatusCode() +
        //                    ' - ' +
        //                    err.getMessage());
        //    }
        //}       

        return thisStore;
    }

    public class LookupSearchResult {

        private Id id;
        private String sObjectType;
        private String icon;
        private String title;
        private String subtitle;
    
        public LookupSearchResult(Id id, String sObjectType, String icon, String title, String subtitle) {
            this.id = id;
            this.sObjectType = sObjectType;
            this.icon = icon;
            this.title = title;
            this.subtitle = subtitle;
        }
    
        @AuraEnabled
        public Id getId() {
            return id;
        }
    
        @AuraEnabled
        public String getSObjectType() {
            return sObjectType;
        }
    
        @AuraEnabled
        public String getIcon() {
            return icon;
        }
    
        @AuraEnabled
        public String getTitle() {
            return title;
        }
    
        @AuraEnabled
        public String getSubtitle() {
            return subtitle;
        }
    }
}